export ONLINE_REVIEW_SOURCE_ROOT=/home/u14/git/tc/tc-online-review
export ONLINE_REVIEW_DEPLOYMENT_DIR=/home/u14/git/tc/tmp
export DISABLE_ONLINE_REVIEW=0
export DISABLE_AUTO_PILOT=0
export DISABLE_LATE_DELIVERABLES_TRACKER=0
export DISABLE_REVIEW_ASSIGNMENT=0
